/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.registry.student.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * Student
 */

public class Student {

	@JsonProperty("age")
	private Integer age = null;

	@JsonProperty("email")
	private String email = null;

	@JsonProperty("firstName")
	private String firstName = null;

	@JsonProperty("gender")
	private String gender = null;

	@JsonProperty("lastName")
	private String lastName = null;

	@JsonProperty("registrationNumber")
	private String registrationNumber = null;

	@JsonProperty("semester")
	private Integer semester = null;

	@JsonProperty("studyCourse")
	private String studyCourse = null;

	@JsonProperty("subgroup")
	private String subgroup = null;

	@JsonProperty("telNr")
	private String telNr = null;

	public Student age(Integer age) {
		this.age = age;
		return this;
	}

	/**
	 * Get age
	 * 
	 * @return age
	 **/
	@ApiModelProperty(value = "")
	public Integer getAge() {
		return age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public Student email(String email) {
		this.email = email;
		return this;
	}

	/**
	 * Get email
	 * 
	 * @return email
	 **/
	@ApiModelProperty(value = "")
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Student firstName(String firstName) {
		this.firstName = firstName;
		return this;
	}

	/**
	 * Get firstName
	 * 
	 * @return firstName
	 **/
	@ApiModelProperty(value = "")
	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public Student gender(String gender) {
		this.gender = gender;
		return this;
	}

	/**
	 * Get gender
	 * 
	 * @return gender
	 **/
	@ApiModelProperty(value = "")
	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Student lastName(String lastName) {
		this.lastName = lastName;
		return this;
	}

	/**
	 * Get lastName
	 * 
	 * @return lastName
	 **/
	@ApiModelProperty(value = "")
	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Student registrationNumber(String registrationNumber) {
		this.registrationNumber = registrationNumber;
		return this;
	}

	/**
	 * Get registrationNumber
	 * 
	 * @return registrationNumber
	 **/
	@ApiModelProperty(value = "")
	public String getRegistrationNumber() {
		return registrationNumber;
	}

	public void setRegistrationNumber(String registrationNumber) {
		this.registrationNumber = registrationNumber;
	}

	public Student semester(Integer semester) {
		this.semester = semester;
		return this;
	}

	/**
	 * Get semester
	 * 
	 * @return semester
	 **/
	@ApiModelProperty(value = "")
	public Integer getSemester() {
		return semester;
	}

	public void setSemester(Integer semester) {
		this.semester = semester;
	}

	public Student studyCourse(String studyCourse) {
		this.studyCourse = studyCourse;
		return this;
	}

	/**
	 * Get studyCourse
	 * 
	 * @return studyCourse
	 **/
	@ApiModelProperty(value = "")
	public String getStudyCourse() {
		return studyCourse;
	}

	public void setStudyCourse(String studyCourse) {
		this.studyCourse = studyCourse;
	}

	public Student subgroup(String subgroup) {
		this.subgroup = subgroup;
		return this;
	}

	/**
	 * Get subgroup
	 * 
	 * @return subgroup
	 **/
	@ApiModelProperty(value = "")
	public String getSubgroup() {
		return subgroup;
	}

	public void setSubgroup(String subgroup) {
		this.subgroup = subgroup;
	}

	public Student telNr(String telNr) {
		this.telNr = telNr;
		return this;
	}

	/**
	 * Get telNr
	 * 
	 * @return telNr
	 **/
	@ApiModelProperty(value = "")
	public String getTelNr() {
		return telNr;
	}

	public void setTelNr(String telNr) {
		this.telNr = telNr;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		Student student = (Student) o;
		return Objects.equals(this.age, student.age) && Objects.equals(this.email, student.email)
				&& Objects.equals(this.firstName, student.firstName) && Objects.equals(this.gender, student.gender)
				&& Objects.equals(this.lastName, student.lastName)
				&& Objects.equals(this.registrationNumber, student.registrationNumber)
				&& Objects.equals(this.semester, student.semester)
				&& Objects.equals(this.studyCourse, student.studyCourse)
				&& Objects.equals(this.subgroup, student.subgroup) && Objects.equals(this.telNr, student.telNr);
	}

	@Override
	public int hashCode() {
		return Objects.hash(age, email, firstName, gender, lastName, registrationNumber, semester, studyCourse,
				subgroup, telNr);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Student {\n");

		sb.append("    age: ").append(toIndentedString(age)).append("\n");
		sb.append("    email: ").append(toIndentedString(email)).append("\n");
		sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
		sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
		sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
		sb.append("    registrationNumber: ").append(toIndentedString(registrationNumber)).append("\n");
		sb.append("    semester: ").append(toIndentedString(semester)).append("\n");
		sb.append("    studyCourse: ").append(toIndentedString(studyCourse)).append("\n");
		sb.append("    subgroup: ").append(toIndentedString(subgroup)).append("\n");
		sb.append("    telNr: ").append(toIndentedString(telNr)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
