/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.registry.course.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * Course
 */

public class Course {


	  @JsonProperty("courseId")
	  private String courseId = null;

	  @JsonProperty("ects")
	  private Integer ects = null;

	  @JsonProperty("professorList")
	  private List<String> professorList = null;

	  @JsonProperty("semester")
	  private Integer semester = null;

	  @JsonProperty("shortSubject")
	  private String shortSubject = null;

	  @JsonProperty("subject")
	  private String subject = null;

	  public Course courseId(String courseId) {
	    this.courseId = courseId;
	    return this;
	  }

	   /**
	   * Get courseId
	   * @return courseId
	  **/
	  @ApiModelProperty(value = "")
	  public String getCourseId() {
	    return courseId;
	  }

	  public void setCourseId(String courseId) {
	    this.courseId = courseId;
	  }

	  public Course ects(Integer ects) {
	    this.ects = ects;
	    return this;
	  }

	   /**
	   * Get ects
	   * @return ects
	  **/
	  @ApiModelProperty(value = "")
	  public Integer getEcts() {
	    return ects;
	  }

	  public void setEcts(Integer ects) {
	    this.ects = ects;
	  }

	  public Course professorList(List<String> professorList) {
	    this.professorList = professorList;
	    return this;
	  }

	  public Course addProfessorListItem(String professorListItem) {
	    if (this.professorList == null) {
	      this.professorList = new ArrayList<String>();
	    }
	    this.professorList.add(professorListItem);
	    return this;
	  }

	   /**
	   * Get professorList
	   * @return professorList
	  **/
	  @ApiModelProperty(value = "")
	  public List<String> getProfessorList() {
	    return professorList;
	  }

	  public void setProfessorList(List<String> professorList) {
	    this.professorList = professorList;
	  }

	  public Course semester(Integer semester) {
	    this.semester = semester;
	    return this;
	  }

	   /**
	   * Get semester
	   * @return semester
	  **/
	  @ApiModelProperty(value = "")
	  public Integer getSemester() {
	    return semester;
	  }

	  public void setSemester(Integer semester) {
	    this.semester = semester;
	  }

	  public Course shortSubject(String shortSubject) {
	    this.shortSubject = shortSubject;
	    return this;
	  }

	   /**
	   * Get shortSubject
	   * @return shortSubject
	  **/
	  @ApiModelProperty(value = "")
	  public String getShortSubject() {
	    return shortSubject;
	  }

	  public void setShortSubject(String shortSubject) {
	    this.shortSubject = shortSubject;
	  }

	  public Course subject(String subject) {
	    this.subject = subject;
	    return this;
	  }

	   /**
	   * Get subject
	   * @return subject
	  **/
	  @ApiModelProperty(value = "")
	  public String getSubject() {
	    return subject;
	  }

	  public void setSubject(String subject) {
	    this.subject = subject;
	  }


	  @Override
	  public boolean equals(java.lang.Object o) {
	    if (this == o) {
	      return true;
	    }
	    if (o == null || getClass() != o.getClass()) {
	      return false;
	    }
	    Course course = (Course) o;
	    return Objects.equals(this.courseId, course.courseId) &&
	        Objects.equals(this.ects, course.ects) &&
	        Objects.equals(this.professorList, course.professorList) &&
	        Objects.equals(this.semester, course.semester) &&
	        Objects.equals(this.shortSubject, course.shortSubject) &&
	        Objects.equals(this.subject, course.subject);
	  }

	  @Override
	  public int hashCode() {
	    return Objects.hash(courseId, ects, professorList, semester, shortSubject, subject);
	  }


	  @Override
	  public String toString() {
	    StringBuilder sb = new StringBuilder();
	    sb.append("class Course {\n");
	    
	    sb.append("    courseId: ").append(toIndentedString(courseId)).append("\n");
	    sb.append("    ects: ").append(toIndentedString(ects)).append("\n");
	    sb.append("    professorList: ").append(toIndentedString(professorList)).append("\n");
	    sb.append("    semester: ").append(toIndentedString(semester)).append("\n");
	    sb.append("    shortSubject: ").append(toIndentedString(shortSubject)).append("\n");
	    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
	    sb.append("}");
	    return sb.toString();
	  }

	  /**
	   * Convert the given object to string with each line indented by 4 spaces
	   * (except the first line).
	   */
	  private String toIndentedString(java.lang.Object o) {
	    if (o == null) {
	      return "null";
	    }
	    return o.toString().replace("\n", "\n    ");
	  }
	  
	}

