/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.registry.exam.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import org.joda.time.DateTime;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * Exam
 */

public class Exam {


	  @JsonProperty("classroom")
	  private String classroom = null;

	  @JsonProperty("courseId")
	  private String courseId = null;

	  @JsonProperty("date")
	  private String date = null;

	  @JsonProperty("duration")
	  private String duration = null;

	  @JsonProperty("examId")
	  private String examId = null;

	  @JsonProperty("numberOfEnrolledStudents")
	  private Integer numberOfEnrolledStudents = null;

	  @JsonProperty("professorId")
	  private String professorId = null;

	  @JsonProperty("studentList")
	  private List<String> studentList = null;

	  @JsonProperty("totalPlaces")
	  private Integer totalPlaces = null;

	  public Exam classroom(String classroom) {
	    this.classroom = classroom;
	    return this;
	  }

	   /**
	   * Get classroom
	   * @return classroom
	  **/
	  @ApiModelProperty(value = "")
	  public String getClassroom() {
	    return classroom;
	  }

	  public void setClassroom(String classroom) {
	    this.classroom = classroom;
	  }

	  public Exam courseId(String courseId) {
	    this.courseId = courseId;
	    return this;
	  }

	   /**
	   * Get courseId
	   * @return courseId
	  **/
	  @ApiModelProperty(value = "")
	  public String getCourseId() {
	    return courseId;
	  }

	  public void setCourseId(String courseId) {
	    this.courseId = courseId;
	  }

	  public Exam date(String date) {
	    this.date = date;
	    return this;
	  }

	   /**
	   * Get date
	   * @return date
	  **/
	  @ApiModelProperty(value = "")
	  public String getDate() {
	    return date;
	  }

	  public void setDate(String date) {
	    this.date = date;
	  }

	  public Exam duration(String duration) {
	    this.duration = duration;
	    return this;
	  }

	   /**
	   * Get duration
	   * @return duration
	  **/
	  @ApiModelProperty(value = "")
	  public String getDuration() {
	    return duration;
	  }

	  public void setDuration(String duration) {
	    this.duration = duration;
	  }

	  public Exam examId(String examId) {
	    this.examId = examId;
	    return this;
	  }

	   /**
	   * Get examId
	   * @return examId
	  **/
	  @ApiModelProperty(value = "")
	  public String getExamId() {
	    return examId;
	  }

	  public void setExamId(String examId) {
	    this.examId = examId;
	  }

	  public Exam numberOfEnrolledStudents(Integer numberOfEnrolledStudents) {
	    this.numberOfEnrolledStudents = numberOfEnrolledStudents;
	    return this;
	  }

	   /**
	   * Get numberOfEnrolledStudents
	   * @return numberOfEnrolledStudents
	  **/
	  @ApiModelProperty(value = "")
	  public Integer getNumberOfEnrolledStudents() {
	    return numberOfEnrolledStudents;
	  }

	  public void setNumberOfEnrolledStudents(Integer numberOfEnrolledStudents) {
	    this.numberOfEnrolledStudents = numberOfEnrolledStudents;
	  }

	  public Exam professorId(String professorId) {
	    this.professorId = professorId;
	    return this;
	  }

	   /**
	   * Get professorId
	   * @return professorId
	  **/
	  @ApiModelProperty(value = "")
	  public String getProfessorId() {
	    return professorId;
	  }

	  public void setProfessorId(String professorId) {
	    this.professorId = professorId;
	  }

	  public Exam studentList(List<String> studentList) {
	    this.studentList = studentList;
	    return this;
	  }

	  public Exam addStudentListItem(String studentListItem) {
	    if (this.studentList == null) {
	      this.studentList = new ArrayList<String>();
	    }
	    this.studentList.add(studentListItem);
	    return this;
	  }

	   /**
	   * Get studentList
	   * @return studentList
	  **/
	  @ApiModelProperty(value = "")
	  public List<String> getStudentList() {
	    return studentList;
	  }

	  public void setStudentList(List<String> studentList) {
	    this.studentList = studentList;
	  }

	  public Exam totalPlaces(Integer totalPlaces) {
	    this.totalPlaces = totalPlaces;
	    return this;
	  }

	   /**
	   * Get totalPlaces
	   * @return totalPlaces
	  **/
	  @ApiModelProperty(value = "")
	  public Integer getTotalPlaces() {
	    return totalPlaces;
	  }

	  public void setTotalPlaces(Integer totalPlaces) {
	    this.totalPlaces = totalPlaces;
	  }


	  @Override
	  public boolean equals(java.lang.Object o) {
	    if (this == o) {
	      return true;
	    }
	    if (o == null || getClass() != o.getClass()) {
	      return false;
	    }
	    Exam exam = (Exam) o;
	    return Objects.equals(this.classroom, exam.classroom) &&
	        Objects.equals(this.courseId, exam.courseId) &&
	        Objects.equals(this.date, exam.date) &&
	        Objects.equals(this.duration, exam.duration) &&
	        Objects.equals(this.examId, exam.examId) &&
	        Objects.equals(this.numberOfEnrolledStudents, exam.numberOfEnrolledStudents) &&
	        Objects.equals(this.professorId, exam.professorId) &&
	        Objects.equals(this.studentList, exam.studentList) &&
	        Objects.equals(this.totalPlaces, exam.totalPlaces);
	  }

	  @Override
	  public int hashCode() {
	    return Objects.hash(classroom, courseId, date, duration, examId, numberOfEnrolledStudents, professorId, studentList, totalPlaces);
	  }


	  @Override
	  public String toString() {
	    StringBuilder sb = new StringBuilder();
	    sb.append("class Exam {\n");
	    
	    sb.append("    classroom: ").append(toIndentedString(classroom)).append("\n");
	    sb.append("    courseId: ").append(toIndentedString(courseId)).append("\n");
	    sb.append("    date: ").append(toIndentedString(date)).append("\n");
	    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
	    sb.append("    examId: ").append(toIndentedString(examId)).append("\n");
	    sb.append("    numberOfEnrolledStudents: ").append(toIndentedString(numberOfEnrolledStudents)).append("\n");
	    sb.append("    professorId: ").append(toIndentedString(professorId)).append("\n");
	    sb.append("    studentList: ").append(toIndentedString(studentList)).append("\n");
	    sb.append("    totalPlaces: ").append(toIndentedString(totalPlaces)).append("\n");
	    sb.append("}");
	    return sb.toString();
	  }

	  /**
	   * Convert the given object to string with each line indented by 4 spaces
	   * (except the first line).
	   */
	  private String toIndentedString(java.lang.Object o) {
	    if (o == null) {
	      return "null";
	    }
	    return o.toString().replace("\n", "\n    ");
	  }
	  
	}

