/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.registry.professor.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Professor
 */

public class Professor {
  @JsonProperty("age")
  private Integer age = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("firstName")
  private String firstName = null;

  @JsonProperty("gender")
  private String gender = null;

  @JsonProperty("lastName")
  private String lastName = null;

  @JsonProperty("professorId")
  private String professorId = null;

  @JsonProperty("telNr")
  private String telNr = null;

  @JsonProperty("title")
  private String title = null;

  public Professor age(Integer age) {
    this.age = age;
    return this;
  }

   /**
   * Get age
   * @return age
  **/
  @ApiModelProperty(value = "")
  public Integer getAge() {
    return age;
  }

  public void setAge(Integer age) {
    this.age = age;
  }

  public Professor email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public Professor firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public Professor gender(String gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  @ApiModelProperty(value = "")
  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }

  public Professor lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public Professor professorId(String professorId) {
    this.professorId = professorId;
    return this;
  }

   /**
   * Get professorId
   * @return professorId
  **/
  @ApiModelProperty(value = "")
  public String getProfessorId() {
    return professorId;
  }

  public void setProfessorId(String professorId) {
    this.professorId = professorId;
  }

  public Professor telNr(String telNr) {
    this.telNr = telNr;
    return this;
  }

   /**
   * Get telNr
   * @return telNr
  **/
  @ApiModelProperty(value = "")
  public String getTelNr() {
    return telNr;
  }

  public void setTelNr(String telNr) {
    this.telNr = telNr;
  }

  public Professor title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Professor professor = (Professor) o;
    return Objects.equals(this.age, professor.age) &&
        Objects.equals(this.email, professor.email) &&
        Objects.equals(this.firstName, professor.firstName) &&
        Objects.equals(this.gender, professor.gender) &&
        Objects.equals(this.lastName, professor.lastName) &&
        Objects.equals(this.professorId, professor.professorId) &&
        Objects.equals(this.telNr, professor.telNr) &&
        Objects.equals(this.title, professor.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(age, email, firstName, gender, lastName, professorId, telNr, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Professor {\n");
    
    sb.append("    age: ").append(toIndentedString(age)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    professorId: ").append(toIndentedString(professorId)).append("\n");
    sb.append("    telNr: ").append(toIndentedString(telNr)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

